# Generated by Django 4.2.2 on 2023-06-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='desc',
            new_name='title',
        ),
    ]
